#!/bin/sh

#LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/Run_Comparison_m/${LABEL}"; TITLE="Medium HIP-safe ID"; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="All runs"' ZmmTP_DataB_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Run B"' ZmmTP_DataC_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="Run C"' ZmmTP_DataD_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Run D"' ZmmTP_DataE_Fits_${LABEL}.root:${LABEL}:'MarkerColor=5,LineColor=5,MarkerStyle=21,Title="Run E"' ZmmTP_DataF_Fits_${LABEL}.root:${LABEL}:'MarkerColor=6,LineColor=6,MarkerStyle=21,Title="Run F"' ZmmTP_DataG_Fits_${LABEL}.root:${LABEL}:'MarkerColor=7,LineColor=7,MarkerStyle=21,Title="Run G"' ZmmTP_DataH_Fits_${LABEL}.root:${LABEL}:'MarkerColor=8,LineColor=8,MarkerStyle=21,Title="Run H"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/Run_Comparison_m/${LABEL}"; TITLE="Iso_{rel} < 0.15"; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="All runs"' ZmmTP_DataB_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Run B"' ZmmTP_DataC_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="Run C"' ZmmTP_DataD_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Run D"' ZmmTP_DataE_Fits_${LABEL}.root:${LABEL}:'MarkerColor=5,LineColor=5,MarkerStyle=21,Title="Run E"' ZmmTP_DataF_Fits_${LABEL}.root:${LABEL}:'MarkerColor=6,LineColor=6,MarkerStyle=21,Title="Run F"' ZmmTP_DataG_Fits_${LABEL}.root:${LABEL}:'MarkerColor=7,LineColor=7,MarkerStyle=21,Title="Run G"' ZmmTP_DataH_Fits_${LABEL}.root:${LABEL}:'MarkerColor=8,LineColor=8,MarkerStyle=21,Title="Run H"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/Run_Comparison_m/${LABEL}"; TITLE="Trg IsoMu22"; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="All runs"' ZmmTP_DataB_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Run B"' ZmmTP_DataC_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="Run C"' ZmmTP_DataD_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Run D"' ZmmTP_DataE_Fits_${LABEL}.root:${LABEL}:'MarkerColor=5,LineColor=5,MarkerStyle=21,Title="Run E"' ZmmTP_DataF_Fits_${LABEL}.root:${LABEL}:'MarkerColor=6,LineColor=6,MarkerStyle=21,Title="Run F"' ZmmTP_DataG_Fits_${LABEL}.root:${LABEL}:'MarkerColor=7,LineColor=7,MarkerStyle=21,Title="Run G"' ZmmTP_DataH_Fits_${LABEL}.root:${LABEL}:'MarkerColor=8,LineColor=8,MarkerStyle=21,Title="Run H"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="TrgOR_Iso_pt_eta_bins"; SMALL="eff.TrgOR_Iso"; DIR="output/Run_Comparison_m/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22"; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="All runs"' ZmmTP_DataB_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Run B"' ZmmTP_DataC_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="Run C"' ZmmTP_DataD_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Run D"' ZmmTP_DataE_Fits_${LABEL}.root:${LABEL}:'MarkerColor=5,LineColor=5,MarkerStyle=21,Title="Run E"' ZmmTP_DataF_Fits_${LABEL}.root:${LABEL}:'MarkerColor=6,LineColor=6,MarkerStyle=21,Title="Run F"' ZmmTP_DataG_Fits_${LABEL}.root:${LABEL}:'MarkerColor=7,LineColor=7,MarkerStyle=21,Title="Run G"' ZmmTP_DataH_Fits_${LABEL}.root:${LABEL}:'MarkerColor=8,LineColor=8,MarkerStyle=21,Title="Run H"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg24_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/Run_Comparison_m/${LABEL}"; TITLE="Trg IsoMu24"; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="All runs"' ZmmTP_DataB_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Run B"' ZmmTP_DataC_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="Run C"' ZmmTP_DataD_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Run D"' ZmmTP_DataE_Fits_${LABEL}.root:${LABEL}:'MarkerColor=5,LineColor=5,MarkerStyle=21,Title="Run E"' ZmmTP_DataF_Fits_${LABEL}.root:${LABEL}:'MarkerColor=6,LineColor=6,MarkerStyle=21,Title="Run F"' ZmmTP_DataG_Fits_${LABEL}.root:${LABEL}:'MarkerColor=7,LineColor=7,MarkerStyle=21,Title="Run G"' ZmmTP_DataH_Fits_${LABEL}.root:${LABEL}:'MarkerColor=8,LineColor=8,MarkerStyle=21,Title="Run H"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}



#LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/Run_Comparison_e/${LABEL}"; TITLE="Non-trig MVA ID"; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="All runs"' ZeeTP_DataB_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Run B"' ZeeTP_DataC_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="Run C"' ZeeTP_DataD_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Run D"' ZeeTP_DataE_Fits_${LABEL}.root:${LABEL}:'MarkerColor=5,LineColor=5,MarkerStyle=21,Title="Run E"' ZeeTP_DataF_Fits_${LABEL}.root:${LABEL}:'MarkerColor=6,LineColor=6,MarkerStyle=21,Title="Run F"' ZeeTP_DataG_Fits_${LABEL}.root:${LABEL}:'MarkerColor=7,LineColor=7,MarkerStyle=21,Title="Run G"' ZeeTP_DataH_Fits_${LABEL}.root:${LABEL}:'MarkerColor=8,LineColor=8,MarkerStyle=21,Title="Run H"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/Run_Comparison_e/${LABEL}"; TITLE="Iso_{rel} < 0.10"; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="All runs"' ZeeTP_DataB_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Run B"' ZeeTP_DataC_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="Run C"' ZeeTP_DataD_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Run D"' ZeeTP_DataE_Fits_${LABEL}.root:${LABEL}:'MarkerColor=5,LineColor=5,MarkerStyle=21,Title="Run E"' ZeeTP_DataF_Fits_${LABEL}.root:${LABEL}:'MarkerColor=6,LineColor=6,MarkerStyle=21,Title="Run F"' ZeeTP_DataG_Fits_${LABEL}.root:${LABEL}:'MarkerColor=7,LineColor=7,MarkerStyle=21,Title="Run G"' ZeeTP_DataH_Fits_${LABEL}.root:${LABEL}:'MarkerColor=8,LineColor=8,MarkerStyle=21,Title="Run H"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/Run_Comparison_e/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="All runs"' ZeeTP_DataB_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Run B"' ZeeTP_DataC_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="Run C"' ZeeTP_DataD_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Run D"' ZeeTP_DataE_Fits_${LABEL}.root:${LABEL}:'MarkerColor=5,LineColor=5,MarkerStyle=21,Title="Run E"' ZeeTP_DataF_Fits_${LABEL}.root:${LABEL}:'MarkerColor=6,LineColor=6,MarkerStyle=21,Title="Run F"' ZeeTP_DataG_Fits_${LABEL}.root:${LABEL}:'MarkerColor=7,LineColor=7,MarkerStyle=21,Title="Run G"' ZeeTP_DataH_Fits_${LABEL}.root:${LABEL}:'MarkerColor=8,LineColor=8,MarkerStyle=21,Title="Run H"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#ABEL="Trg27_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/Run_Comparison_e/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight"; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="All runs"' ZeeTP_DataB_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Run B"' ZeeTP_DataC_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="Run C"' ZeeTP_DataD_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Run D"' ZeeTP_DataE_Fits_${LABEL}.root:${LABEL}:'MarkerColor=5,LineColor=5,MarkerStyle=21,Title="Run E"' ZeeTP_DataF_Fits_${LABEL}.root:${LABEL}:'MarkerColor=6,LineColor=6,MarkerStyle=21,Title="Run F"' ZeeTP_DataG_Fits_${LABEL}.root:${LABEL}:'MarkerColor=7,LineColor=7,MarkerStyle=21,Title="Run G"' ZeeTP_DataH_Fits_${LABEL}.root:${LABEL}:'MarkerColor=8,LineColor=8,MarkerStyle=21,Title="Run H"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27Loose_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/Run_Comparison_e/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose"; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="All runs"' ZeeTP_DataB_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Run B"' ZeeTP_DataC_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="Run C"' ZeeTP_DataD_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Run D"' ZeeTP_DataE_Fits_${LABEL}.root:${LABEL}:'MarkerColor=5,LineColor=5,MarkerStyle=21,Title="Run E"' ZeeTP_DataF_Fits_${LABEL}.root:${LABEL}:'MarkerColor=6,LineColor=6,MarkerStyle=21,Title="Run F"' ZeeTP_DataG_Fits_${LABEL}.root:${LABEL}:'MarkerColor=7,LineColor=7,MarkerStyle=21,Title="Run G"' ZeeTP_DataH_Fits_${LABEL}.root:${LABEL}:'MarkerColor=8,LineColor=8,MarkerStyle=21,Title="Run H"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}