#!/bin/sh

DO_MUONS=1
DO_ELECS=1

if [ ${DO_MUONS} -eq 1 ]; then

LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="Medium (HIP-safe for B to F) ID"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.15"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso1_pt_eta_bins"; SMALL="eff.AIso1"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso2_pt_eta_bins"; SMALL="eff.AIso2"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg24_Iso_pt_eta_bins"; SMALL="eff.Trg24_Iso"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="Trg IsoMu24"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg24OR_Iso_pt_eta_bins"; SMALL="eff.Trg24OR_Iso"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="Trg IsoMu24 | Trg IsoTkMu24"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="ID_pt_eta_finebins"; SMALL="eff.ID"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="Medium (HIP-safe for B to F) ID"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_finebins"; SMALL="eff.Iso"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.15"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="IDIso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="ID && Iso_{rel} < 0.15"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="TrgOR4_Iso_pt_eta_bins"; SMALL="eff.TrgOR4_Iso"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR4_AIso1_pt_bins_inc_eta"; SMALL="eff.TrgOR4_AIso1_eta_inc"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR4_AIso2_pt_bins_inc_eta"; SMALL="eff.TrgOR4_AIso2_eta_inc"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR4_AIso1_pt_eta_bins"; SMALL="eff.TrgOR4_AIso1"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR4_AIso2_pt_eta_bins"; SMALL="eff.TrgOR4_AIso2"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="TrgOR5_Iso_pt_eta_bins"; SMALL="eff.TrgOR5_Iso"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR5_AIso1_pt_bins_inc_eta"; SMALL="eff.TrgOR5_AIso1_eta_inc"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Tau120 | Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR5_AIso2_pt_bins_inc_eta"; SMALL="eff.TrgOR5_AIso2_eta_inc"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Tau120 | Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR5_AIso1_pt_eta_bins"; SMALL="eff.TrgOR5_AIso1"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Tau120 | Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR5_AIso2_pt_eta_bins"; SMALL="eff.TrgOR5_AIso2"; DIR="output/genMuon_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Tau120 | Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC; python scripts/truthTagAndProbe.py genMuon_truth/genMuon_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC; python scripts/plotEffSlices.py genMuon_truth/genMuon_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genMuon_truth/genMuon_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

fi

if [ ${DO_ELECS} -eq 1 ]; then

LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Non-trig MVA ID 16"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.10"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso1_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso2_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso1_pt_eta_bins"; SMALL="eff.Trg_AIso1"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_eta_bins"; SMALL="eff.Trg_AIso2"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="TrgOR_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Tau120 | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_AIso1_pt_eta_bins"; SMALL="eff.Trg_AIso1"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Tau120 | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_AIso2_pt_eta_bins"; SMALL="eff.Trg_AIso2"; DIR="output/genElectron_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_EmbeddingData.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding_data --isMC --particle 'e'; python scripts/truthTagAndProbe.py genElectron_truth/genElectron_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python scripts/plotEffSlices.py genElectron_truth/genElectron_EmbeddingData_Fits_${LABEL}.root:${LABEL}:'Title="EmbeddingData"' genElectron_truth/genElectron_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=3,LineColor=3,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

fi
