#!/bin/sh

DO_MUONS=0
DO_ELECS=1

if [ ${DO_MUONS} -eq 1 ]; then

LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Medium (HIP-safe for B to F) ID"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="IDTrk_pt_eta_bins"; SMALL="eff.IDTrk"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Medium HIP-safe ID"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding  --bin-replace 500,2.3,150,2.3; python scripts/fitTagAndProbe.py v16_3/ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC  --bin-replace 500,2.3,150,2.3; #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.15"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso1_pt_eta_bins"; SMALL="eff.AIso1"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso2_pt_eta_bins"; SMALL="eff.AIso2"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="TrgOR_Iso_pt_eta_bins"; SMALL="eff.TrgOR_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="TrgOR3_Iso_pt_eta_bins"; SMALL="eff.TrgOR3_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg24_Iso_pt_eta_bins"; SMALL="eff.Trg24_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu24"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg24OR_Iso_pt_eta_bins"; SMALL="eff.Trg24OR_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu24 | Trg IsoTkMu24"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg24OR3_Iso_pt_eta_bins"; SMALL="eff.Trg24OR3_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu24 | IsoTkMu24 | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="TrgMT_Iso_pt_eta_bins"; SMALL="eff.TrgMT_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu19PFTau20"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="TrgMTL1_Iso_pt_eta_bins"; SMALL="eff.TrgMTL1_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu19PFTau20SingleL1"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="ID_pt_eta_finebins"; SMALL="eff.ID"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Medium (HIP-safe for B to F) ID"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_finebins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.15"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="IDIso_pt_eta_bins"; SMALL="eff.IdIso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="ID && Iso_{rel} < 0.15"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="TrgOR4_Iso_pt_eta_bins"; SMALL="eff.TrgOR4_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR4_AIso1_pt_bins_inc_eta"; SMALL="eff.TrgOR4_AIso1_eta_inc"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR4_AIso2_pt_bins_inc_eta"; SMALL="eff.TrgOR4_AIso2_eta_inc"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR4_AIso1_pt_eta_bins"; SMALL="eff.TrgOR4_AIso1"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR4_AIso2_pt_eta_bins"; SMALL="eff.TrgOR4_AIso2"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="TrgOR5_Iso_pt_eta_bins"; SMALL="eff.TrgOR5_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR5_AIso1_pt_bins_inc_eta"; SMALL="eff.TrgOR5_AIso1_eta_inc"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Tau120 | Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR5_AIso2_pt_bins_inc_eta"; SMALL="eff.TrgOR5_AIso2_eta_inc"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Tau120 | Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR5_AIso1_pt_eta_bins"; SMALL="eff.TrgOR5_AIso1"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Tau120 | Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR5_AIso2_pt_eta_bins"; SMALL="eff.TrgOR5_AIso2"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22 | IsoMu22_eta2p1 | IsoTkMu22_eta2p1 | Tau120 | Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py output/ZmmTP_MC.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}



fi

if [ ${DO_ELECS} -eq 1 ]; then

LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Non-trig MVA ID 16"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.10"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso1_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso2_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso1_pt_eta_bins"; SMALL="eff.Trg_AIso1"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_eta_bins"; SMALL="eff.Trg_AIso2"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


#LABEL="Trg27_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27_AIso1_pt_eta_bins"; SMALL="eff.Trg_AIso1"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27_AIso2_pt_eta_bins"; SMALL="eff.Trg_AIso2"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


#LABEL="Trg27Loose_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27Loose_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27Loose_AIso1_pt_eta_bins"; SMALL="eff.Trg_AIso1"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27Loose_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27Loose_AIso2_pt_eta_bins"; SMALL="eff.Trg_AIso2"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}



LABEL="TrgOR_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Tau120 | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_AIso1_pt_eta_bins"; SMALL="eff.Trg_AIso1"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Tau120 | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_AIso2_pt_eta_bins"; SMALL="eff.Trg_AIso2"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


#LABEL="Trg27OR_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27OR_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight | Tau120 | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27OR_AIso1_pt_eta_bins"; SMALL="eff.Trg_AIso1"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27OR_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight | Tau120 | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27OR_AIso2_pt_eta_bins"; SMALL="eff.Trg_AIso2"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPTight | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


#LABEL="Trg27LooseOR_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27LooseOR_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose | Tau120 | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27LooseOR_AIso1_pt_eta_bins"; SMALL="eff.Trg_AIso1"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27LooseOR_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose | Tau120 | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#LABEL="Trg27LooseOR_AIso2_pt_eta_bins"; SMALL="eff.Trg_AIso2"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele27eta2p1WPLoose | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

#DESYlike
LABEL="DESYtag_ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Non-trig MVA ID 16"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="DESYtag_Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.10"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="DESYtag_Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="DESYtagNonSC_ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Non-trig MVA ID 16"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="DESYtagNonSC_Iso_pt_eta_bins"; SMALL="eff.IdIso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.10"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="DESYtagNonSC_IDIso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Non-trig MVA ID 16 && Iso_{rel} < 0.10"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="DESYtagNonSC_Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

for CUT in 26 30 34 37 40 43 46 50; do
LABEL="TrgTag${CUT}_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | L1_pt > ${CUT}"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgTagReco${CUT}_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | L1_pt > ${CUT}"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
done
fi
