#!/bin/sh

DO_MUONS=1
DO_ELECS=1

if [ ${DO_MUONS} -eq 1 ]; then


LABEL="Trg_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE=""; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso1_pt_eta_bins"; SMALL="eff.Trg_AIso1"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE=""; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE=""; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_eta_bins"; SMALL="eff.Trg_AIso2"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE=""; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Medium (HIP-safe for B to F) ID"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #  #python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.15"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="LooseIso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.2"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso1_pt_eta_bins"; SMALL="eff.AIso1"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso2_pt_eta_bins"; SMALL="eff.AIso2"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="Trg_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_Iso"; DIR="JUL17/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py JUL17/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py HERE_JUN17/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' HERE_JUN17/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"' JUL17/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,1.0 --ratio-to 0  --label-pos 3 --ratio-y-range 0.95,1.2 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_Iso"; DIR="JUL17/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py JUL17/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py HERE_JUN17/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' HERE_JUN17/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"' JUL17/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,1.0 --ratio-to 0  --label-pos 3 --ratio-y-range 0.95,1.2 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg24_Iso_pt_eta_bins"; SMALL="eff.Trg24_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; python scripts/fitTagAndProbe.py output/ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data;  #  #python scripts/plotEffSlices.py v16_3/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' v16_3/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="Trg24_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg24_Iso"; DIR="JUL17/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py JUL17/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py HERE_JUN17/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' HERE_JUN17/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"' JUL17/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,1.0 --ratio-to 0  --label-pos 3 --ratio-y-range 0.95,1.2 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg24_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg24_Iso"; DIR="JUL17/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py JUL17/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py HERE_JUN17/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' HERE_JUN17/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"' JUL17/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,1.0 --ratio-to 0  --label-pos 3 --ratio-y-range 0.95,1.2 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

fi

if [ ${DO_ELECS} -eq 1 ]; then

LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Non-trig MVA ID 16"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.10"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="LooseIso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.15"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso1_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso2_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg35_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg35_AIso1inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg35_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg35_AIso2inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="Trg35_Iso_pt_eta_bins"; SMALL="eff.Trg35_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py output/ZeeTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data --particle 'e';  #python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Monte Carlo"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="Embedding"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


fi
