#!/bin/sh

DO_MUONS=1
DO_ELECS=0

if [ ${DO_MUONS} -eq 1 ]; then

LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Medium ID"; BKG="CMSShape"; SIG="DoubleVCorr"; ###python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding;   
python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"'  output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.8,1.0 --ratio-y-range 0.8,1.2 --ratio-to 0 --label-pos 3 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
#output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"'
#LABEL="IDTrk_pt_eta_bins"; SMALL="eff.IDTrk"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Medium HIP-safe ID"; BKG="CMSShape"; SIG="DoubleVCorr"; ###python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding  --bin-replace 500,2.3,150,2.3; ##python scripts/fitTagAndProbe.py output/ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC  --bin-replace 500,2.3,150,2.3; python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.6,1.0 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.15"; BKG="Exponential"; SIG="DoubleVCorr"; ###python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.6,1.0 --ratio-y-range 0.8,1.2 --ratio-to 0 --label-pos 3 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
#output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"' 

LABEL="AIso1_pt_eta_bins"; SMALL="eff.AIso1"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"'  output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 3 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
#output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"'

LABEL="AIso2_pt_eta_bins"; SMALL="eff.AIso2"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 3 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
#output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"' 

LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,1.0 --ratio-to 0  --label-pos 3 --ratio-y-range 0.95,1.2 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
#output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"'

LABEL="Trg_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,1.0 --ratio-to 0  --label-pos 3 --ratio-y-range 0.95,1.2 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
#output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"'

LABEL="Trg_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,1.0 --ratio-to 0  --label-pos 3 --ratio-y-range 0.95,1.2 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
#output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"'

LABEL="Trg24_Iso_pt_eta_bins"; SMALL="eff.Trg24_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu24"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,1.0 --label-pos 3 --ratio-y-range 0.95,1.2 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
#output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"'


LABEL="Trg24_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg24_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu24"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,1.0 --label-pos 3 --ratio-y-range 0.95,1.2 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
#output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"'

LABEL="Trg24_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg24_Iso"; DIR="output/tag_and_probe_m_v16_3/${LABEL}"; TITLE="Trg IsoMu24"; BKG="Exponential"; SIG="DoubleVCorr"; ##python scripts/fitTagAndProbe.py output/ZmmTP_Embedding.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding; #  
python scripts/plotEffSlices.py output/ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZmmTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow#mu embedded"' --y-range 0.0,1.0 --label-pos 3 --ratio-y-range 0.95,1.2 --ratio-to 0 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
#output/ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow#mu#mu simulation"'

fi

if [ ${DO_ELECS} -eq 1 ]; then

LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="MVA ID 16"; BKG="CMSShape"; SIG="DoubleVCorr"; #python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; #python scripts/fitTagAndProbe.py output/ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python 
python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow ee simulation"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow e embedded"' --y-range 0.4,1.05 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} < 0.10"; BKG="Exponential"; SIG="DoubleVCorr"; #python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; #python scripts/fitTagAndProbe.py output/ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python 
python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow ee simulation"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow e embedded"' --y-range 0.6,1.05 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso1_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; #python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; #python scripts/fitTagAndProbe.py output/ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python 
python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow ee simulation"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow e embedded"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso2_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; #python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; #python scripts/fitTagAndProbe.py output/ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python 
python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow ee simulation"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow e embedded"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}


LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25"; BKG="Exponential"; SIG="DoubleVCorr"; #python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; #python scripts/fitTagAndProbe.py output/ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python 
python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow ee simulation"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow e embedded"' --y-range 0.0,1.0 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; #python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; #python scripts/fitTagAndProbe.py output/ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python 
python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow ee simulation"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow e embedded"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2inc"; DIR="output/tag_and_probe_e_v16_3/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; #python scripts/fitTagAndProbe.py output/ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/embedding --particle 'e'; #python scripts/fitTagAndProbe.py output/ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc --isMC --particle 'e'; python 
python scripts/plotEffSlices.py output/ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' output/ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="Z#rightarrow ee simulation"' output/ZeeTP_Embedding_Fits_${LABEL}.root:${LABEL}:'MarkerColor=4,LineColor=4,MarkerStyle=21,Title="#mu#rightarrow e embedded"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 0 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

done
fi
